### PR TITLE
Swift support, improved styling support

### PR DESCRIPTION
**Pull request by Legoless**
This pull request adds 3 features:
- Swift API enhanced compatibility with Nullability modifiers
- Ability to style buttons added to the alert view by providing a custom block 
- Ability to choose color for button separator

### CODE REVIEW

**Comment by kubatruhlar** [comment]
Nice job, would you mind to remove extra double spaces (line 135 etc.) and space behind the \* (like line 94, 24 etc.)?

**Comment by Legoless** [comment]
Something like this? :)

**Comment by kubatruhlar** [comment]
I mean `UIButton* btn` should be `UIButton *btn` in .h and in .m as well. Otherwise its good 👍

**Comment by Legoless** [comment]
I'm not sure what you mean, they are the same on both sides?

**Comment by kubatruhlar** [comment]
It's just a style preference, the space doesn't mean anything in this case, but keep the style of this code please.

**Comment by Legoless** [comment]
Of course, I'm keeping style the same, but maybe just Xcode formats it in a way I cannot see what you want changed. Can you be more specific?

**Comment by kubatruhlar** [comment]
Don't you see space after asterix? Everywhere you put `UIButton* btn`, you are supposed to put the space before not after the asterix.

**Comment by Legoless** [comment]
Oh yeah, that's what you mean, sorry :) Fixed now, I hope.

**Pull request merged**
